Repository hashicorp/packer-plugin-vsphere, pull requests merged in 2022-12, with the labels that each got.

#239 docs: update support references
  docs/builders/vsphere-clone.mdx
  docs/builders/vsphere-iso.mdx
  docs/builders/vsphere-supervisor.mdx
Labels: docs, builder/vsphere-iso, builder/vsphere-clone, builder/vsphere-supervisor

#178 feat: Add customization for Windows guest OS
  builder/vsphere/clone/step_customize.go
  builder/vsphere/clone/step_customize.hcl2spec.go
  docs-partials/builder/vsphere/clone/CustomizeConfig-not-required.mdx
  docs-partials/builder/vsphere/clone/WindowsOptions-not-required.mdx
Labels: enhancement

#240 chore(deps): bump vmware/govmomi from v0.26.1 to v0.29.0
  builder/vsphere/driver/vm.go
  go.mod
  go.sum
Labels: dependencies, chore
