Repository hashicorp/packer-plugin-vsphere, pull requests merged in 2023-11, with the labels that each got.

#315 fix: log errors prior to logout
  builder/vsphere/driver/vm.go
Labels: bug

#319 chore(deps): golang.org/x/net
  go.mod
  go.sum
Labels: dependencies, chore

#320 chore(deps): google.golang.org/grpc
  go.mod
  go.sum
Labels: dependencies, chore

#321 Update Supervisor test to skip output from retry
  builder/vsphere/supervisor/step_watch_source.go
  builder/vsphere/supervisor/utils_test.go
Labels: tech-debt, builder/vsphere-supervisor

#323 fix: update vsphere-supervisor test to skip output from retry (follow-up)
  builder/vsphere/supervisor/utils_test.go
Labels: chore, builder/vsphere-supervisor

#318 feat: Add support for Virtualization Based Security
  builder/vsphere/clone/builder.go
  builder/vsphere/clone/config.go
  builder/vsphere/clone/config.hcl2spec.go
  builder/vsphere/common/step_add_flag.go
  builder/vsphere/common/step_add_flag.hcl2spec.go
  builder/vsphere/common/step_add_flag_test.go
  builder/vsphere/driver/vm.go
  builder/vsphere/driver/vm_mock.go
  builder/vsphere/iso/builder.go
  builder/vsphere/iso/config.go
  builder/vsphere/iso/config.hcl2spec.go
  docs-partials/builder/vsphere/common/FlagConfig-not-required.mdx
Labels: enhancement, builder/vsphere-iso, builder/vsphere-clone

#322 chore(deps): bump `github.com/vmware/govmomi` from 0.29.0 to 0.33.1
  .github/dependabot.yml
  builder/vsphere/driver/library.go
  builder/vsphere/driver/vm.go
  go.mod
  go.sum
Labels: dependencies, chore
