Repository hashicorp/packer-plugin-vsphere, pull requests merged in 2024-03, with the labels that each got.

#372 docs: use example.com
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/common/testing/utility.go
  builder/vsphere/driver/datastore_acc_test.go
  builder/vsphere/driver/driver_test.go
  builder/vsphere/driver/resource_pool_acc_test.go
  builder/vsphere/examples/alpine/alpine-3.8.json
  builder/vsphere/examples/alpine/alpine-3.8.pkr.hcl
  builder/vsphere/examples/clone/alpine.json
  builder/vsphere/examples/clone/alpine.pkr.hcl
  builder/vsphere/examples/driver/main.go
  builder/vsphere/examples/macos/macos-10.13.json
  builder/vsphere/examples/macos/macos-10.13.pkr.hcl
  builder/vsphere/examples/ubuntu/ubuntu-16.04.json
  builder/vsphere/examples/ubuntu/ubuntu-16.04.pkr.hcl
  builder/vsphere/examples/windows/windows-10.json
  builder/vsphere/examples/windows/windows-10.pkr.hcl
  builder/vsphere/iso/builder_acc_test.go
  docs/builders/vsphere-clone.mdx
  docs/builders/vsphere-iso.mdx
Labels: documentation

#370 chore: correct typos and markdown
  CHANGELOG.md
  README.md
  builder/vsphere/clone/config_test.go
  builder/vsphere/clone/step_clone_test.go
  builder/vsphere/clone/step_customize.go
  builder/vsphere/clone/step_customize_test.go
  builder/vsphere/common/hcp_metadata.go
  builder/vsphere/common/step_wait_for_ip.go
  builder/vsphere/driver/disk_test.go
  builder/vsphere/driver/library.go
  builder/vsphere/driver/vm.go
  builder/vsphere/driver/vm_clone_acc_test.go
  builder/vsphere/iso/builder_acc_test.go
  builder/vsphere/iso/step_create_test.go
  post-processor/vsphere/artifact_test.go
  post-processor/vsphere/post-processor_test.go
Labels: chore

#371 docs: `vsphere-clone` customize
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/clone/step_customize.go
  builder/vsphere/common/step_hardware.go
  builder/vsphere/common/storage_config.go
  docs-partials/builder/vsphere/clone/CustomizeConfig-not-required.mdx
  docs-partials/builder/vsphere/clone/CustomizeConfig.mdx
  docs-partials/builder/vsphere/clone/GlobalDnsSettings-not-required.mdx
  docs-partials/builder/vsphere/clone/GlobalDnsSettings.mdx
  docs-partials/builder/vsphere/clone/GlobalRoutingSettings-not-required.mdx
  docs-partials/builder/vsphere/clone/GlobalRoutingSettings.mdx
  docs-partials/builder/vsphere/clone/LinuxOptions-not-required.mdx
  docs-partials/builder/vsphere/clone/NetworkInterface-not-required.mdx
  docs-partials/builder/vsphere/clone/WindowsOptions-not-required.mdx
  docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx
  docs-partials/builder/vsphere/common/StorageConfig-not-required.mdx
Labels: documentation

#374 docs: update `vsphere/clone/step_clone`
  .web-docs/components/builder/vsphere-clone/README.md
  builder/vsphere/clone/step_clone.go
  docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx
  docs-partials/builder/vsphere/clone/vAppConfig-not-required.mdx
Labels: documentation

#373 docs: update clone/iso config
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/clone/config.go
  builder/vsphere/iso/config.go
  docs-partials/builder/vsphere/clone/Config-not-required.mdx
  docs-partials/builder/vsphere/iso/Config-not-required.mdx
Labels: documentation

#369 docs: update `vsphere/iso/step_create`
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/iso/step_create.go
  docs-partials/builder/vsphere/iso/CreateConfig-not-required.mdx
  docs-partials/builder/vsphere/iso/NIC-not-required.mdx
  docs-partials/builder/vsphere/iso/NIC-required.mdx
Labels: documentation

#376 chore: remove ovpn files
  builder/vsphere/test/lab.ovpn
  builder/vsphere/test/lab.p12
  builder/vsphere/test/test-key.pem
  builder/vsphere/test/test-key.pub
Labels: chore

#375 Update Jenkins template example for supervisor builder
  builder/vsphere/examples/supervisor/jenkins-template.pkr.hcl
Labels: documentation

#377 docs: update `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation, chore

#378 docs(examples): remove macos
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/examples/macos/macos-10.13.json
  builder/vsphere/examples/macos/macos-10.13.pkr.hcl
  builder/vsphere/examples/macos/setup/.gitignore
  builder/vsphere/examples/macos/setup/iso-macos.sh
  builder/vsphere/examples/macos/setup/iso-setup.sh
  builder/vsphere/examples/macos/setup/postinstall
  builder/vsphere/examples/macos/setup/setup.sh
  docs/builders/vsphere-clone.mdx
  docs/builders/vsphere-iso.mdx
Labels: documentation, chore

#385 chore(post-processor): update `vsphere-template`
  .web-docs/components/post-processor/vsphere-template/README.md
  docs-partials/post-processor/vsphere-template/Config-not-required.mdx
  docs-partials/post-processor/vsphere-template/Config-required.mdx
  docs-partials/post-processor/vsphere/Config-not-required.mdx
  docs/post-processors/vsphere-template.mdx
  post-processor/vsphere-template/post-processor.go
  post-processor/vsphere-template/post-processor.hcl2spec.go
  post-processor/vsphere-template/post-processor_test.go
  post-processor/vsphere-template/step_choose_datacenter.go
  post-processor/vsphere-template/step_create_folder.go
  post-processor/vsphere-template/step_create_snapshot.go
  post-processor/vsphere-template/step_mark_as_template.go
Labels: post-processor/vsphere-template, chore

#387 chore(post-processor): update `vsphere`
  .web-docs/components/post-processor/vsphere/README.md
  docs-partials/post-processor/vsphere/Config-not-required.mdx
  docs-partials/post-processor/vsphere/Config-required.mdx
  docs/post-processors/vsphere.mdx
  post-processor/vsphere/post-processor.go
  post-processor/vsphere/post-processor.hcl2spec.go
Labels: post-processor/vsphere, chore

#388 common: make sure to prepend remote iso path
  builder/vsphere/common/step_add_cdrom.go
  builder/vsphere/common/step_add_cdrom_test.go
Labels: bug, regression

#384 GNUmakefile: make dev uses packer for install
  GNUmakefile
Labels: ignore-for-release, chore

#389 chore(deps): bump google.golang.org/protobuf from v1.31.0 to v1.33.0
  go.mod
  go.sum
Labels: dependencies, chore

#390 chore(deps): bump github.com/go-jose/go-jose/v3 from v3.0.1 to v3.0.3
  go.mod
  go.sum
Labels: dependencies, chore
