Repository hashicorp/packer-plugin-vsphere, pull requests merged in 2024-02, with the labels that each got.

#355 refactor: only add / remove minimul number of cdroms
  builder/vsphere/common/step_add_cdrom.go
  builder/vsphere/common/step_add_cdrom_test.go
  builder/vsphere/common/step_reattach_cdrom.go
  builder/vsphere/common/step_reattach_cdrom_test.go
  builder/vsphere/driver/vm.go
  builder/vsphere/driver/vm_cdrom.go
  builder/vsphere/driver/vm_mock.go
Labels: chore

#359 feat: add `windows_sysprep_text` field
  .web-docs/components/builder/vsphere-clone/README.md
  builder/vsphere/clone/config.go
  builder/vsphere/clone/step_customize.go
  builder/vsphere/clone/step_customize.hcl2spec.go
  builder/vsphere/clone/step_customize_test.go
  docs-partials/builder/vsphere/clone/CustomizeConfig-not-required.mdx
Labels: enhancement, builder/vsphere-clone

#367 feat: add support for precision clock device
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/clone/config.hcl2spec.go
  builder/vsphere/common/step_hardware.go
  builder/vsphere/common/step_hardware.hcl2spec.go
  builder/vsphere/common/step_hardware_test.go
  builder/vsphere/driver/vm.go
  builder/vsphere/driver/vm_test.go
  builder/vsphere/iso/config.hcl2spec.go
  docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx
Labels: enhancement
