Repository hashicorp/packer-plugin-vsphere, pull requests merged in 2024-05, with the labels that each got.

#401 docs: fix links and options
  .web-docs/components/builder/vsphere-clone/README.md
  docs/builders/vsphere-clone.mdx
Labels: documentation

#412 chore(deps): bump golang/x/net from 0.21.0 to 0.24.0
  go.mod
  go.sum
Labels: dependencies, chore

#422 chore(deps): bump github.com/vmware/govmomi from 0.36.2 to 0.37.1
  builder/vsphere/driver/vm_test.go
  go.mod
  go.sum
Labels: dependencies, chore

#411 docs: `disk_size`
  .web-docs/components/builder/vsphere-clone/README.md
  builder/vsphere/clone/step_clone.go
  builder/vsphere/driver/disk.go
  builder/vsphere/driver/vm.go
  docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx
Labels: documentation, builder/vsphere-clone

#263 feat: add support for dynamic directpath i/o
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/clone/config.hcl2spec.go
  builder/vsphere/common/step_hardware.go
  builder/vsphere/common/step_hardware.hcl2spec.go
  builder/vsphere/common/step_hardware_test.go
  builder/vsphere/driver/vm.go
  builder/vsphere/iso/config.hcl2spec.go
  docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx
  docs-partials/builder/vsphere/common/PCIPassthroughAllowedDevice-not-required.mdx
  docs-partials/builder/vsphere/common/PCIPassthroughAllowedDevice.mdx
  docs/builders/vsphere-iso.mdx
Labels: enhancement

#413 fix: ovftool error handling
  post-processor/vsphere/post-processor.go
Labels: bug, post-processor/vsphere

#414 fix: multiple network error msg
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/clone/step_clone.go
  builder/vsphere/driver/network.go
  builder/vsphere/driver/vm.go
  builder/vsphere/iso/step_create.go
  docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx
  docs-partials/builder/vsphere/iso/NIC-not-required.mdx
Labels: bug, builder/vsphere-iso, builder/vsphere-clone

#416 feat: set template name
  .web-docs/components/post-processor/vsphere-template/README.md
  docs-partials/post-processor/vsphere-template/Config-not-required.mdx
  post-processor/vsphere-template/post-processor.go
  post-processor/vsphere-template/post-processor.hcl2spec.go
  post-processor/vsphere-template/step_mark_as_template.go
Labels: enhancement, post-processor/vsphere-template

#415 feat: option to remove network adapters
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/clone/builder.go
  builder/vsphere/clone/config.go
  builder/vsphere/clone/config.hcl2spec.go
  builder/vsphere/common/step_remove_network_adapter.go
  builder/vsphere/common/step_remove_network_adapter.hcl2spec.go
  builder/vsphere/common/step_remove_network_adapter_test.go
  builder/vsphere/driver/vm.go
  builder/vsphere/driver/vm_mock.go
  builder/vsphere/iso/builder.go
  builder/vsphere/iso/config.go
  builder/vsphere/iso/config.hcl2spec.go
  docs-partials/builder/vsphere/common/RemoveNetworkAdapterConfig-not-required.mdx
  docs-partials/builder/vsphere/common/RemoveNetworkConfig-not-required.mdx
  docs/builders/vsphere-clone.mdx
  docs/builders/vsphere-iso.mdx
Labels: enhancement, builder/vsphere-iso, builder/vsphere-clone

#417 docs: update `README.md`
  .web-docs/README.md
  README.md
  docs/README.md
Labels: documentation

#409 feat: add support for export to ova
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/clone/builder.go
  builder/vsphere/common/step_export.go
  builder/vsphere/common/step_export.hcl2spec.go
  builder/vsphere/common/step_import_to_content_library.go
  builder/vsphere/iso/builder.go
  docs-partials/builder/vsphere/common/ContentLibraryDestinationConfig-not-required.mdx
  docs-partials/builder/vsphere/common/ExportConfig-not-required.mdx
Labels: enhancement, builder/vsphere-iso

#427 fix: run once command list
  .web-docs/components/builder/vsphere-clone/README.md
  builder/vsphere/clone/step_customize.go
  docs-partials/builder/vsphere/clone/WindowsOptions-not-required.mdx
Labels: bug

#428 docs: update `vsphere-clone`
  .web-docs/components/builder/vsphere-clone/README.md
  builder/vsphere/clone/config.go
  builder/vsphere/clone/step_clone.go
  builder/vsphere/clone/step_customize.go
  docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx
  docs-partials/builder/vsphere/clone/Config-not-required.mdx
  docs-partials/builder/vsphere/clone/CustomizeConfig-not-required.mdx
  docs-partials/builder/vsphere/clone/CustomizeConfig.mdx
  docs-partials/builder/vsphere/clone/GlobalDnsSettings-not-required.mdx
  docs-partials/builder/vsphere/clone/GlobalDnsSettings.mdx
  docs-partials/builder/vsphere/clone/GlobalRoutingSettings-not-required.mdx
  docs-partials/builder/vsphere/clone/GlobalRoutingSettings.mdx
  docs-partials/builder/vsphere/clone/LinuxOptions-not-required.mdx
  docs-partials/builder/vsphere/clone/NetworkInterface-not-required.mdx
  docs-partials/builder/vsphere/clone/WindowsOptions-not-required.mdx
  docs-partials/builder/vsphere/clone/vAppConfig-not-required.mdx
Labels: documentation

#429 docs: update links
  .web-docs/README.md
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  .web-docs/components/post-processor/vsphere/README.md
  README.md
  builder/vsphere/common/step_config_params.go
  builder/vsphere/common/step_hardware.go
  builder/vsphere/iso/step_create.go
  docs-partials/builder/vsphere/common/ConfigParamsConfig-not-required.mdx
  docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx
  docs-partials/builder/vsphere/iso/CreateConfig-not-required.mdx
  docs-partials/post-processor/vsphere/Config-not-required.mdx
  docs/README.md
  post-processor/vsphere/post-processor.go
Labels: documentation
