Repository hashicorp/packer-plugin-vsphere, pull requests merged in 2024-04, with the labels that each got.

#394 fix: use cdroms len instead of ISOPaths len
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/common/step_add_cdrom_test.go
  builder/vsphere/common/step_reattach_cdrom.go
  builder/vsphere/common/step_reattach_cdrom_test.go
  builder/vsphere/driver/vm.go
  builder/vsphere/driver/vm_cdrom.go
  builder/vsphere/driver/vm_cdrom_test.go
  builder/vsphere/driver/vm_mock.go
  docs/builders/vsphere-iso.mdx
Labels: bug, regression

#396 docs: update external documentation links
  .web-docs/components/builder/vsphere-iso/README.md
  .web-docs/components/builder/vsphere-supervisor/README.md
  docs/builders/vsphere-iso.mdx
  docs/builders/vsphere-supervisor.mdx
Labels: documentation

#379 feat: upload max retries
  .web-docs/components/post-processor/vsphere/README.md
  docs-partials/post-processor/vsphere/Config-not-required.mdx
  post-processor/vsphere/post-processor.go
  post-processor/vsphere/post-processor.hcl2spec.go
Labels: enhancement, post-processor/vsphere

#404 fix: skip unix-style permissions
  builder/vsphere/common/output_config.go
Labels: tech-debt

#406 fix: ipv6 rfc2732
  builder/vsphere/common/step_wait_for_ip.go
Labels: bug

#405 [HPR-1702] build: Add LICENSE file to release artifacts
  .goreleaser.yml
Labels: legal

#399 feat: local and remote cache options
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/common/step_download.go
  builder/vsphere/common/step_remote_upload.go
  builder/vsphere/common/step_remote_upload_test.go
  builder/vsphere/iso/builder.go
  builder/vsphere/iso/config.go
  builder/vsphere/iso/config.hcl2spec.go
  docs-partials/builder/vsphere/iso/Config-not-required.mdx
Labels: enhancement, builder/vsphere-iso
