Repository hashicorp/packer-plugin-vsphere, pull requests merged in 2024-01, with the labels that each got.

#350 chore(deps): github.com/go-jose/go-jose/v3
  go.mod
  go.sum
Labels: dependencies, chore

#349 docs: update `disk_size` from mb to mib
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  builder/vsphere/clone/step_clone.go
  builder/vsphere/common/storage_config.go
  docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx
  docs-partials/builder/vsphere/common/DiskConfig-not-required.mdx
  docs-partials/builder/vsphere/common/DiskConfig-required.mdx
Labels: documentation

#353 fix: remove obsolete path check
  post-processor/vsphere-template/post-processor.go
Labels: bug

#327 feat: add option to reattach cdroms
  builder/vsphere/clone/builder.go
  builder/vsphere/clone/config.go
  builder/vsphere/clone/config.hcl2spec.go
  builder/vsphere/common/step_add_cdrom.go
  builder/vsphere/common/step_add_cdrom_test.go
  builder/vsphere/common/step_reattach_cdrom.go
  builder/vsphere/common/step_reattach_cdrom.hcl2spec.go
  builder/vsphere/common/step_reattach_cdrom_test.go
  builder/vsphere/common/step_remove_cdrom.go
  builder/vsphere/common/step_remove_cdrom_test.go
  builder/vsphere/driver/vm_mock.go
  builder/vsphere/iso/builder.go
  builder/vsphere/iso/config.go
  builder/vsphere/iso/config.hcl2spec.go
  docs-partials/builder/vsphere/common/ReattachCDRomConfig-not-required.mdx
Labels: enhancement, builder/vsphere-iso, builder/vsphere-clone

#352 chore(tests): remove unnecessary `AddCdromCalled`
  builder/vsphere/common/step_add_cdrom_test.go
  builder/vsphere/common/step_reattach_cdrom_test.go
  builder/vsphere/driver/vm_mock.go
Labels: tech-debt, chore

#361 chore: address `io/ioutil` depreciation
  builder/vsphere/clone/step_customize.go
  builder/vsphere/common/step_ssh_key_pair.go
  builder/vsphere/driver/datastore_acc_test.go
  builder/vsphere/iso/builder_acc_test.go
  builder/vsphere/iso/step_create_test.go
  builder/vsphere/supervisor/step_create_source.go
  builder/vsphere/supervisor/step_create_source_test.go
Labels: dependencies, chore
