Repository hashicorp/packer-plugin-vsphere, pull requests merged in 2024-06, with the labels that each got.

#438 fix: support content library item uuid for hcp
  .DS_Store
  builder/vsphere/common/hcp_metadata.go
  builder/vsphere/common/step_import_to_content_library.go
  builder/vsphere/driver/library.go
  builder/vsphere/driver/vm.go
Labels: bug, hcp

#437 fix: don't assume driver isn't nil in StepConnect
  builder/vsphere/common/step_connect.go
Labels: bug

#441 chore: add issues `config.yml`
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore

#442 chore: update `golangci.yml`
  .golangci.yml
Labels: chore

#443 fix: use mixed caps
  builder/vsphere/clone/step_customize.go
  builder/vsphere/common/step_add_cdrom.go
  builder/vsphere/driver/vm.go
  builder/vsphere/driver/vm_mock.go
  post-processor/vsphere/post-processor.go
  post-processor/vsphere/post-processor_test.go
Labels: tech-debt

#444 refactor: use `ui.Sayf` and `ui.Errorf`
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  .web-docs/components/builder/vsphere-supervisor/README.md
  builder/vsphere/common/step_boot_command.go
  builder/vsphere/common/step_download.go
  builder/vsphere/common/step_export.go
  builder/vsphere/common/step_import_to_content_library.go
  builder/vsphere/common/step_remote_upload.go
  builder/vsphere/common/step_remove_floppy.go
  builder/vsphere/common/step_run.go
  builder/vsphere/common/step_shutdown.go
  builder/vsphere/common/step_ssh_key_pair.go
  builder/vsphere/common/step_template.go
  builder/vsphere/common/step_wait_for_ip.go
  builder/vsphere/driver/vm.go
  builder/vsphere/supervisor/utils.go
  go.mod
  go.sum
  post-processor/vsphere-template/step_mark_as_template.go
Labels: chore

#445 refactor: post-processor ui errors
  post-processor/vsphere-template/step_choose_datacenter.go
  post-processor/vsphere-template/step_create_folder.go
  post-processor/vsphere-template/step_create_snapshot.go
  post-processor/vsphere-template/step_mark_as_template.go
Labels: ignore-for-release, refactor

#446 chore: update use of `err.Error()`
  builder/vsphere/driver/library.go
  builder/vsphere/driver/vm.go
Labels: ignore-for-release, chore

#447 chore: update supervisor plugin example jenkins template
  examples/builder/vsphere-supervisor/jenkins-template.pkr.hcl
Labels: docs, chore

#433 feat: import ovf template from url in supervisor builder
  .gitignore
  .web-docs/components/builder/vsphere-supervisor/README.md
  builder/vsphere/supervisor/builder.go
  builder/vsphere/supervisor/config.go
  builder/vsphere/supervisor/config.hcl2spec.go
  builder/vsphere/supervisor/config_test.go
  builder/vsphere/supervisor/step_create_source.go
  builder/vsphere/supervisor/step_create_source.hcl2spec.go
  builder/vsphere/supervisor/step_create_source_test.go
  builder/vsphere/supervisor/step_import_image.go
  builder/vsphere/supervisor/step_import_image.hcl2spec.go
  builder/vsphere/supervisor/step_import_image_test.go
  docs-partials/builder/vsphere/supervisor/CreateSourceConfig-not-required.mdx
  docs-partials/builder/vsphere/supervisor/CreateSourceConfig-required.mdx
  docs-partials/builder/vsphere/supervisor/ImportImageConfig-not-required.mdx
  docs/builders/vsphere-supervisor.mdx
  examples/builder/vsphere-supervisor/general-template-with-image-import.pkr.hcl
  go.mod
  go.sum
Labels: enhancement, builder/vsphere-supervisor

#448 refactor(tests): standardize messages
  builder/vsphere/clone/config_test.go
  builder/vsphere/clone/step_clone_test.go
  builder/vsphere/clone/step_customize_test.go
  builder/vsphere/common/artifact_test.go
  builder/vsphere/common/cleanup_vm.go
  builder/vsphere/common/cleanup_vm_test.go
  builder/vsphere/common/hcp_metadata_test.go
  builder/vsphere/common/step_add_cdrom_test.go
  builder/vsphere/common/step_add_flag_test.go
  builder/vsphere/common/step_add_floppy_test.go
  builder/vsphere/common/step_boot_command.go
  builder/vsphere/common/step_download_test.go
  builder/vsphere/common/step_hardware_test.go
  builder/vsphere/common/step_http_ip_discover_test.go
  builder/vsphere/common/step_reattach_cdrom_test.go
  builder/vsphere/common/step_remote_upload_test.go
  builder/vsphere/common/step_remove_cdrom_test.go
  builder/vsphere/common/step_remove_floppy_test.go
  builder/vsphere/common/step_remove_network_adapter_test.go
  builder/vsphere/common/step_run.go
  builder/vsphere/common/step_wait_for_ip.go
  builder/vsphere/driver/datastore_acc_test.go
  builder/vsphere/driver/datastore_test.go
  builder/vsphere/driver/disk_test.go
  builder/vsphere/driver/driver_test.go
  builder/vsphere/driver/folder_acc_test.go
  builder/vsphere/driver/host_acc_test.go
  builder/vsphere/driver/library_test.go
  builder/vsphere/driver/resource_pool_acc_test.go
  builder/vsphere/driver/resource_pool_test.go
  builder/vsphere/driver/vm_cdrom_test.go
  builder/vsphere/driver/vm_test.go
  builder/vsphere/iso/builder_acc_test.go
  builder/vsphere/iso/step_create_test.go
  builder/vsphere/supervisor/config_test.go
  builder/vsphere/supervisor/step_connect_supervisor_test.go
  builder/vsphere/supervisor/step_create_source_test.go
  builder/vsphere/supervisor/step_publish_source_test.go
  builder/vsphere/supervisor/step_validate_publish_test.go
  builder/vsphere/supervisor/step_watch_source_test.go
  builder/vsphere/supervisor/utils_test.go
  post-processor/vsphere/artifact_test.go
  post-processor/vsphere/post-processor_test.go
Labels: ignore-for-release, refactor

#450 chore(deps): hashicorp/go-retryablehttp
  go.mod
  go.sum
Labels: dependencies, chore
