Repository hashicorp/packer-plugin-vsphere, pull requests merged in 2025-01, with the labels that each got.

#489 fix: `vsphere-clone`: rearrange build steps to ensure source VM exists before deleting target
  builder/vsphere/clone/step_clone.go
  builder/vsphere/clone/step_clone_test.go
Labels: bug

#504 chore(deps): bump golang.org/x/ dependencies
  go.mod
  go.sum
Labels: dependencies, chore

#505 chore(docs): update links
  .web-docs/components/builder/vsphere-clone/README.md
  .web-docs/components/builder/vsphere-iso/README.md
  .web-docs/components/builder/vsphere-supervisor/README.md
  README.md
  builder/vsphere/clone/step_customize.go
  builder/vsphere/common/step_hardware.go
  builder/vsphere/common/storage_config.go
  docs-partials/builder/vsphere/clone/CustomizeConfig.mdx
  docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx
  docs-partials/builder/vsphere/common/StorageConfig-not-required.mdx
  docs/builders/vsphere-iso.mdx
  docs/builders/vsphere-supervisor.mdx
Labels: documentation, chore

#510 chore: driver godoc
  builder/vsphere/driver/cluster.go
  builder/vsphere/driver/datastore.go
  builder/vsphere/driver/disk.go
  builder/vsphere/driver/driver.go
  builder/vsphere/driver/folder.go
  builder/vsphere/driver/host.go
  builder/vsphere/driver/library.go
  builder/vsphere/driver/network.go
  builder/vsphere/driver/resource_pool.go
  builder/vsphere/driver/vm.go
  builder/vsphere/driver/vm_cdrom.go
  builder/vsphere/driver/vm_keyboard.go
Labels: tech-debt, chore
