Repository hashicorp/packer-plugin-vsphere, pull requests merged in 2025-05, with the labels that each got.

#526 refactor: remove redundant type
  builder/vsphere/clone/step_customize_test.go
Labels: tech-debt, refactor

#527 refactor: use nil slice declaration
  builder/vsphere/driver/vm.go
Labels: tech-debt, refactor

#528 refactor: omit type declaration
  post-processor/vsphere/post-processor.go
Labels: tech-debt, refactor

#529 refactor: exported functions with unexported return types
  post-processor/vsphere-template/step_create_snapshot.go
  post-processor/vsphere-template/step_mark_as_template.go
Labels: tech-debt, refactor

#530 refactor: replace type assertion on errors
  builder/vsphere/driver/datastore.go
  builder/vsphere/driver/folder.go
  builder/vsphere/driver/resource_pool.go
  builder/vsphere/driver/vm.go
Labels: tech-debt, refactor

#533 chore(gh): bump golangci-lint to v1.60.1
  .github/workflows/go-validate.yml
Labels: chore

#534 chore: update golangci-lint to v2
  .github/workflows/go-validate.yml
  .golangci.yml
  builder/vsphere/clone/builder.go
  builder/vsphere/clone/config_test.go
  builder/vsphere/driver/datastore.go
  builder/vsphere/iso/builder.go
  builder/vsphere/supervisor/builder.go
Labels: tech-debt, chore

#535 fix: type assertion on errors
  builder/vsphere/driver/datastore.go
Labels: tech-debt

#501 feat: add ISO support in supervisor builder
  .web-docs/components/builder/vsphere-supervisor/README.md
  builder/vsphere/supervisor/config.hcl2spec.go
  builder/vsphere/supervisor/config_test.go
  builder/vsphere/supervisor/step_connect_supervisor.go
  builder/vsphere/supervisor/step_create_source.go
  builder/vsphere/supervisor/step_create_source.hcl2spec.go
  builder/vsphere/supervisor/step_create_source_test.go
  builder/vsphere/supervisor/step_import_image.go
  builder/vsphere/supervisor/step_import_image_test.go
  builder/vsphere/supervisor/step_publish_source.go
  builder/vsphere/supervisor/step_publish_source_test.go
  builder/vsphere/supervisor/step_watch_source.go
  builder/vsphere/supervisor/step_watch_source_test.go
  builder/vsphere/supervisor/utils_test.go
  docs-partials/builder/vsphere/supervisor/CreateSourceConfig-not-required.mdx
  docs-partials/builder/vsphere/supervisor/ImportImageConfig-not-required.mdx
  docs-partials/builder/vsphere/supervisor/WatchSourceConfig-not-required.mdx
  docs/builders/vsphere-supervisor.mdx
  examples/builder/vsphere-supervisor/general-template-with-image-import.pkr.hcl
  go.mod
  go.sum
Labels: enhancement, breaking-change, builder/vsphere-supervisor
